# Generated by Django 4.2.16 on 2024-11-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('comment', 'Comment'), ('like', 'Like'), ('comment_like', 'Comment Like')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('comment', 'Comment'), ('like', 'Like'), ('comment_like', 'Comment Like')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentlikeview',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='commentlikeview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlikeviewcount',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='commentview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likeview',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likeview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likeviewcount',
            name='like',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article'),
        ),
        migrations.DeleteModel(
            name='ArticleView',
        ),
        migrations.DeleteModel(
            name='CommentLikeView',
        ),
        migrations.DeleteModel(
            name='CommentLikeViewCount',
        ),
        migrations.DeleteModel(
            name='CommentView',
        ),
        migrations.DeleteModel(
            name='LikeView',
        ),
        migrations.DeleteModel(
            name='LikeViewCount',
        ),
    ]
