# Generated by Django 4.2.16 on 2024-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('free', '자유게시판'), ('knowledge', '금융지식 나누기'), ('recommendation', '상품 추천'), ('notice', '공지사항')], default='free', max_length=20),
        ),
    ]
